### ISSUE TITLE
App crashes when Gallery tab is opened

### ISSUE THREAD

**Issue by elaewin** [EvitaAFD/PicFeed#8]
When I try to open the Gallery tab in the simulator, it opens, and then the app crashes.

**Comment by elaewin** [comment]
You're getting a crash if one of the records doesn't have a date, because you're force unwrapping the date. if you move the `let date = record["date"]` up into the `if let` statement, and don't force unwrap it, this should fix the problem.

**Comment by EvitaAFD** [comment]
Fixed it! Thank you.
